export const characters = [
    {
      name: "Artorias",
      game: "Dark Souls",
      origin: "Lordran",
      race: "Human",
      gender: "Male",
      type: "Boss",
      affiliation: "Knights of Gwyn",
    },
    {
      name: "Lady Maria",
      game: "Bloodborne",
      origin: "Cainhurst",
      race: "Vileblood",
      gender: "Female",
      type: "Boss",
      affiliation: "Hunters of Byrgenwerth",
    },
    {
      name: "Maliketh",
      game: "Elden Ring",
      origin: "Farum Azula",
      race: "Beastman",
      gender: "Male",
      type: "Boss",
      affiliation: "Golden Order",
    },
    {
      name: "Gwyn",
      game: "Dark Souls",
      origin: "Lordran",
      race: "God",
      gender: "Male",
      type: "Boss",
      affiliation: "Lord of Sunlight",
    },
    {
      name: "The Witch of Izalith",
      game: "Dark Souls",
      origin: "Lordran",
      race: "Human",
      gender: "Female",
      type: "Boss",
      affiliation: "Witches of Izalith",
    },
    {
      name: "Nito",
      game: "Dark Souls",
      origin: "The Tomb of the Giants",
      race: "Human/Undead",
      gender: "Male",
      type: "Boss",
      affiliation: "The Gravelord Servants",
    },
    {
      name: "Solaire of Astora",
      game: "Dark Souls",
      origin: "Astora",
      race: "Human",
      gender: "Male",
      type: "NPC",
      affiliation: "Warrior of Sunlight",
    },
    {
      name: "Seigmeyer of Catarina",
      game: "Dark Souls",
      origin: "Catarina",
      race: "Human",
      gender: "Male",
      type: "NPC",
      affiliation: "Knights of Catarina",
    },
    {
      name: "Eileen the Crow",
      game: "Bloodborne",
      origin: "Yharnam",
      race: "Human",
      gender: "Female",
      type: "NPC",
      affiliation: "Crow Hunters",
    },
    {
      name: "Father Gascoigne",
      game: "Bloodborne",
      origin: "Yharnam",
      race: "Human",
      gender: "Male",
      type: "Boss",
      affiliation: "Hunters",
    },
    {
      name: "Vicar Amelia",
      game: "Bloodborne",
      origin: "Yharnam",
      race: "Beast",
      gender: "Female",
      type: "Boss",
      affiliation: "The Healing Church",
    },
    {
      name: "Gehrman",
      game: "Bloodborne",
      origin: "The Dream",
      race: "Human",
      gender: "Male",
      type: "Boss",
      affiliation: "Hunter",
    },
    {
      name: "Micolash",
      game: "Bloodborne",
      origin: "Mergo's Loft",
      race: "Human",
      gender: "Male",
      type: "Boss",
      affiliation: "Mensis",
    },
    {
      name: "Radahn",
      game: "Elden Ring",
      origin: "Caelid",
      race: "Demigod",
      gender: "Male",
      type: "Boss",
      affiliation: "Redmane",
    },
    {
      name: "Rykard",
      game: "Elden Ring",
      origin: "Volcano Manor",
      race: "Demigod",
      gender: "Male",
      type: "Boss",
      affiliation: "Volcano Manor",
    },
    {
      name: "Mohg",
      game: "Elden Ring",
      origin: "Subterranean Shunning-Grounds",
      race: "Demigod",
      gender: "Male",
      type: "Boss",
      affiliation: "Moghwyn Dynasty",
    },
    {
      name: "Godrick the Grafted",
      game: "Elden Ring",
      origin: "Stormveil Castle",
      race: "Human/Demigod",
      gender: "Male",
      type: "Boss",
      affiliation: "House Godrick",
    },
    {
      name: "Fia",
      game: "Elden Ring",
      origin: "Roundtable Hold",
      race: "Human",
      gender: "Female",
      type: "NPC",
      affiliation: "The Deathbed Companion",
    },
    {
      name: "Blaidd",
      game: "Elden Ring",
      origin: "Siofra River",
      race: "Wolfman",
      gender: "Male",
      type: "NPC",
      affiliation: "The Three Fingers",
    },
    {
      name: "Patches",
      game: "Elden Ring",
      origin: "Liurnia of the Lakes",
      race: "Human",
      gender: "Male",
      type: "NPC",
      affiliation: "None",
    },
    {
      name: "Vare",
      game: "Elden Ring",
      origin: "Liurnia of the Lakes",
      race: "Human",
      gender: "Male",
      type: "NPC",
      affiliation: "Moor",
    },
    {
      name: "Yuria of Londor",
      game: "Dark Souls 3",
      origin: "Londor",
      race: "Hollow",
      gender: "Female",
      type: "NPC",
      affiliation: "The Hollowed",
    },
    {
      name: "Ludleth of Courland",
      game: "Dark Souls 3",
      origin: "Courland",
      race: "Hollow",
      gender: "Male",
      type: "NPC",
      affiliation: "The Firekeepers",
    },
    {
      name: "Gael",
      game: "Dark Souls 3",
      origin: "The Painted World of Ariandel",
      race: "Human",
      gender: "Male",
      type: "Boss",
      affiliation: "The Painted World",
    },
    {
      name: "Nameless King",
      game: "Dark Souls 3",
      origin: "Archdragon Peak",
      race: "God/Dragon",
      gender: "Male",
      type: "Boss",
      affiliation: "The Ancient Dragons",
    },
    {
      name: "Pontiff Sulyvahn",
      game: "Dark Souls 3",
      origin: "Irithyll of the Boreal Valley",
      race: "Human",
      gender: "Male",
      type: "Boss",
      affiliation: "Boreal Knights",
    },
    {
      name: "Anri of Astora",
      game: "Dark Souls 3",
      origin: "Astora",
      race: "Human",
      gender: "Female",
      type: "NPC",
      affiliation: "Fledgling Knight",
    },
    {
      name: "Siegward of Catarina",
      game: "Dark Souls 3",
      origin: "Catarina",
      race: "Human",
      gender: "Male",
      type: "NPC",
      affiliation: "Knights of Catarina",
    },
    {
      name: "Shura",
      game: "Sekiro",
      origin: "Ashina Castle",
      race: "Human",
      gender: "Male",
      type: "Boss",
      affiliation: "Ashina",
    },
    {
      name: "Isshin Ashina",
      game: "Sekiro",
      origin: "Ashina Castle",
      race: "Human",
      gender: "Male",
      type: "Boss",
      affiliation: "Ashina Clan",
    },
    {
      name: "Genichiro Ashina",
      game: "Sekiro",
      origin: "Ashina Castle",
      race: "Human",
      gender: "Male",
      type: "Boss",
      affiliation: "Ashina Clan",
    },
    {
      name: "Emma",
      game: "Sekiro",
      origin: "Ashina Castle",
      race: "Human",
      gender: "Female",
      type: "NPC",
      affiliation: "Heir to the Dragon",
    },
    {
      name: "Sekiro",
      game: "Sekiro",
      origin: "Ashina",
      race: "Human",
      gender: "Male",
      type: "NPC",
      affiliation: "Shinobi",
    },
    {
      name: "Bloodborne Hunter",
      game: "Bloodborne",
      origin: "Yharnam",
      race: "Human",
      gender: "Male",
      type: "NPC",
      affiliation: "Hunters",
    },
    {
      name: "Godo",
      game: "Sekiro",
      origin: "Senpou Temple",
      race: "Human",
      gender: "Male",
      type: "NPC",
      affiliation: "Senpou Temple",
    },
    {
      name: "Kuro",
      game: "Sekiro",
      origin: "Ashina Castle",
      race: "Human",
      gender: "Male",
      type: "NPC",
      affiliation: "Shinobi",
    },
    {
      name: "Oda Nobunaga",
      game: "Sekiro",
      origin: "Sengoku Japan",
      race: "Human",
      gender: "Male",
      type: "Boss",
      affiliation: "Warlord",
    },
    {
      name: "Tarnished",
      game: "Elden Ring",
      origin: "Unknown",
      race: "Human",
      gender: "Varies",
      type: "NPC",
      affiliation: "Varies",
    }
  ];