export const characters = [
  {
    name: "Artorias",
    game: "Dark Souls",
    origin: "Lordran",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Knights of Gwyn",
    characterIcon: "https://i.ibb.co/bNdxWpY/artorias.png",
    characterImage: ""
  },
  {
    name: "Lady Maria",
    game: "Bloodborne",
    origin: "Cainhurst",
    race: "Vileblood",
    gender: "Female",
    type: "Boss",
    affiliation: "Hunters of Byrgenwerth",
    characterIcon: "https://i.ibb.co/6sNhrtn/lady-Maria.png",
    characterImage: ""
  },
  {
    name: "Maliketh",
    game: "Elden Ring",
    origin: "Farum Azula",
    race: "Beastman",
    gender: "Male",
    type: "Boss",
    characterIcon: "https://i.ibb.co/q9KmCPH/maliketh.png",
    characterImage: ""
  },
  {
    name: "Gwyn",
    game: "Dark Souls",
    origin: "Lordran",
    race: "God",
    gender: "Male",
    type: "Boss",
    affiliation: "Lord of Sunlight",
    characterIcon: "https://i.ibb.co/zVXQyj0/gwyn.png",
    characterImage: ""
  },
  {
    name: "The Witch of Izalith",
    game: "Dark Souls",
    origin: "Lordran",
    race: "Human",
    gender: "Female",
    type: "Boss",
    affiliation: "Witches of Izalith",
    characterIcon: "https://i.ibb.co/7r2J7W0/the-Witch-Of-Izalith.png",
    characterImage: ""
  },
  {
    name: "Nito",
    game: "Dark Souls",
    origin: "The Tomb of the Giants",
    race: "Human/Undead",
    gender: "Male",
    type: "Boss",
    affiliation: "The Gravelord Servants",
    characterIcon: "https://i.ibb.co/dGTH1K1/nito.png",
    characterImage: ""
  },
  {
    name: "Solaire of Astora",
    game: "Dark Souls",
    origin: "Astora",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Warrior of Sunlight",
    characterIcon: "https://i.ibb.co/7nd3rY8/solaire-Of-Astora.png",
    characterImage: ""
  },
  {
    name: "Siegmeyer of Catarina",
    game: "Dark Souls",
    origin: "Catarina",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Knights of Catarina",
    characterIcon: "https://i.ibb.co/WtHTMyd/siegmeyer-Of-Catarina.png",
    characterImage: ""
  },
  {
    name: "Eileen the Crow",
    game: "Bloodborne",
    origin: "Yharnam",
    race: "Human",
    gender: "Female",
    type: "NPC",
    affiliation: "Crow Hunters",
    characterIcon: "https://i.ibb.co/T22Lx4z/eileen-The-Crow.png",
    characterImage: ""
  },
  {
    name: "Father Gascoigne",
    game: "Bloodborne",
    origin: "Yharnam",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Hunters",
    characterIcon: "https://i.ibb.co/RTxwt56/father-Gascoigne.png",
    characterImage: ""
  },
  {
    name: "Vicar Amelia",
    game: "Bloodborne",
    origin: "Yharnam",
    race: "Beast",
    gender: "Female",
    type: "Boss",
    affiliation: "The Healing Church",
    characterIcon: "https://i.ibb.co/pZfx093/vicar-Amelia.png",
    characterImage: ""
  },
  {
    name: "Gehrman",
    game: "Bloodborne",
    origin: "The Dream",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Hunter",
    characterIcon: "https://i.ibb.co/9nbc484/gehrman.png",
    characterImage: ""
  },
  {
    name: "Micolash",
    game: "Bloodborne",
    origin: "Mergo's Loft",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Mensis",
    characterIcon: "https://i.ibb.co/cFWrHRQ/micolash.png",
    characterImage: ""
  },
  {
    name: "Radahn",
    game: "Elden Ring",
    origin: "Caelid",
    race: "Demigod",
    gender: "Male",
    type: "Boss",
    affiliation: "Redmane",
    characterIcon: "https://i.ibb.co/yS6kLRQ/radahn.png",
    characterImage: ""
  },
  {
    name: "Rykard",
    game: "Elden Ring",
    origin: "Volcano Manor",
    race: "Demigod",
    gender: "Male",
    type: "Boss",
    affiliation: "Volcano Manor",
    characterIcon: "https://i.ibb.co/xXhZ1BZ/rykard.png",
    characterImage: ""
  },
  {
    name: "Mohg",
    game: "Elden Ring",
    origin: "Subterranean Shunning-Grounds",
    race: "Demigod",
    gender: "Male",
    type: "Boss",
    affiliation: "Moghwyn Dynasty",
    characterIcon: "https://i.ibb.co/FgfW0q1/mohg.png",
    characterImage: ""
  },
  {
    name: "Godrick the Grafted",
    game: "Elden Ring",
    origin: "Stormveil Castle",
    race: "Human/Demigod",
    gender: "Male",
    type: "Boss",
    affiliation: "House Godrick",
    characterIcon: "https://i.ibb.co/R02qHgB/godrick-The-Grafted.png",
    characterImage: ""
  },
  {
    name: "Fia",
    game: "Elden Ring",
    origin: "Roundtable Hold",
    race: "Human",
    gender: "Female",
    type: "NPC",
    affiliation: "The Deathbed Companion",
    characterIcon: "https://i.ibb.co/x1vHhRF/fia.png",
    characterImage: ""
  },
  {
    name: "Blaidd",
    game: "Elden Ring",
    origin: "Siofra River",
    race: "Wolfman",
    gender: "Male",
    type: "NPC",
    affiliation: "The Three Fingers",
    characterIcon: "https://i.ibb.co/Ht3ZSZs/blaidd.png",
    characterImage: ""
  },
  {
    name: "Patches",
    game: "Elden Ring",
    origin: "Liurnia of the Lakes",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "None",
    characterIcon: "https://i.ibb.co/hdQJS4Q/patches.png",
    characterImage: ""
  },
  {
    name: "Varre",
    game: "Elden Ring",
    origin: "Liurnia of the Lakes",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Moor",
    characterIcon: "https://i.ibb.co/G9Y6mMR/varre.png",
    characterImage: ""
  },
  {
    name: "Yuria of Londor",
    game: "Dark Souls 3",
    origin: "Londor",
    race: "Hollow",
    gender: "Female",
    type: "NPC",
    affiliation: "The Hollowed",
    characterIcon: "https://i.ibb.co/8YNscvc/yuria-Of-Londor.png",
    characterImage: ""
  },
  {
    name: "Ludleth of Courland",
    game: "Dark Souls 3",
    origin: "Courland",
    race: "Hollow",
    gender: "Male",
    type: "NPC",
    affiliation: "The Firekeepers",
    characterIcon: "https://i.ibb.co/LvBFnsX/ludleth-Of-Courland.png",
    characterImage: ""
  },
  {
    name: "Nameless King",
    game: "Dark Souls 3",
    origin: "Archdragon Peak",
    race: "God/Dragon",
    gender: "Male",
    type: "Boss",
    affiliation: "The Ancient Dragons",
    characterIcon: "https://i.ibb.co/dp162Dt/nameless-King.png",
    characterImage: ""
  },
  {
    name: "Pontiff Sulyvahn",
    game: "Dark Souls 3",
    origin: "Irithyll of the Boreal Valley",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Boreal Knights",
    characterIcon: "https://i.ibb.co/80CtrH8/pontiff-Sulyvahn.png",
    characterImage: ""
  },
  {
    name: "Anri of Astora",
    game: "Dark Souls 3",
    origin: "Astora",
    race: "Human",
    gender: "Female",
    type: "NPC",
    affiliation: "Fledgling Knight",
    characterIcon: "https://i.ibb.co/qMnK2cz/anri-Of-Astora.png",
    characterImage: ""
  },
  {
    name: "Siegward of Catarina",
    game: "Dark Souls 3",
    origin: "Catarina",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Knights of Catarina",
    characterIcon: "https://i.ibb.co/t3jMjpt/siegward-Of-Catarina.png",
    characterImage: ""
  },
  {
    name: "Shura",
    game: "Sekiro",
    origin: "Ashina Castle",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Ashina",
    characterIcon: "https://i.ibb.co/0q0XJvN/shura.png",
    characterImage: ""
  },
  {
    name: "Isshin Ashina",
    game: "Sekiro",
    origin: "Ashina Castle",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Ashina Clan",
    characterIcon: "https://i.ibb.co/tsSJT86/isshin-Ashina.png",
    characterImage: ""
  },
  {
    name: "Genichiro Ashina",
    game: "Sekiro",
    origin: "Ashina Castle",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Ashina Clan",
    characterIcon: "https://i.ibb.co/FhHKQ74/genichiro-Ashina.png",
    characterImage: ""
  },
  {
    name: "Emma",
    game: "Sekiro",
    origin: "Ashina Castle",
    race: "Human",
    gender: "Female",
    type: "NPC",
    affiliation: "Heir to the Dragon",
    characterIcon: "https://i.ibb.co/HNNVHV8/emma.png",
    characterImage: ""
  },
  {
    name: "Sekiro",
    game: "Sekiro",
    origin: "Ashina",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Shinobi",
    characterIcon: "https://i.ibb.co/cvqcd0R/sekiro.png",
    characterImage: ""
  },
  {
    name: "Bloodborne Hunter",
    game: "Bloodborne",
    origin: "Yharnam",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Hunters",
    characterIcon: "https://i.ibb.co/yWjnxXq/bloodborne-Hunter.png",
    characterImage: ""
  },
  {
    name: "Godo",
    game: "Sekiro",
    origin: "Senpou Temple",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Senpou Temple",
    characterIcon: "https://i.ibb.co/9cmvggQ/godo.png",
    characterImage: ""
  },
  {
    name: "Kuro",
    game: "Sekiro",
    origin: "Ashina Castle",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Shinobi",
    characterIcon: "https://i.ibb.co/6rJFrx9/kuro.png",
    characterImage: ""
  },
  {
    name: "Oda Nobunaga",
    game: "Sekiro",
    origin: "Sengoku Japan",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Warlord",
    characterIcon: "https://i.ibb.co/f2KXRNs/oda-Nobunaga.png",
    characterImage: ""
  },
  {
    name: "Tarnished",
    game: "Elden Ring",
    origin: "Unknown",
    race: "Human",
    gender: "Varies",
    type: "NPC",
    affiliation: "Varies",
    characterIcon: "https://i.ibb.co/KKKxbBF/tarnished.png",
    characterImage: ""
  },
  {
    name: "Laurence, the First Vicar",
    game: "Bloodborne",
    origin: "Yharnam",
    race: "Beast",
    gender: "Male",
    type: "Boss",
    affiliation: "The Healing Church",
    characterIcon: "https://i.ibb.co/my9DCLn/laurence-The-First-Vicar.png",
    characterImage: ""
  },
  {
    name: "Ornstein",
    game: "Dark Souls",
    origin: "Lordran",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Knights of Gwyn",
    characterIcon: "https://i.ibb.co/pzcxSQF/ornstein.png",
    characterImage: ""
  },
  {
    name: "Smough",
    game: "Dark Souls",
    origin: "Lordran",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Executioners",
    characterIcon: "https://i.ibb.co/LNCPffX/smough.png",
    characterImage: ""
  },
  {
    name: "Malenia",
    game: "Elden Ring",
    origin: "Haligtree",
    race: "Demigod",
    gender: "Female",
    type: "Boss",
    affiliation: "Haligtree Knights",
    characterIcon: "https://i.ibb.co/VH54rcj/malenia.png",
    characterImage: ""
  },
  {
    name: "Ranni the Witch",
    game: "Elden Ring",
    origin: "Liurnia of the Lakes",
    race: "Empyrean",
    gender: "Female",
    type: "NPC",
    affiliation: "Carian Royal Family",
    characterIcon: "https://i.ibb.co/yqZNyLK/ranni-The-Witch.png",
    characterImage: ""
  },
  {
    name: "Gyoubu Masataka Oniwa",
    game: "Sekiro",
    origin: "Ashina",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Ashina Clan",
    characterIcon: "https://i.ibb.co/2Z4Sj9b/Gyoubu.png",
    characterImage: ""
  },
  {
    name: "Lady Butterfly",
    game: "Sekiro",
    origin: "Hirata Estate",
    race: "Human",
    gender: "Female",
    type: "Boss",
    affiliation: "Shinobi",
    characterIcon: "https://i.ibb.co/Mskrycx/quelaag.png",
    characterImage: ""
  },
  {
    name: "The Doll",
    game: "Bloodborne",
    origin: "Hunter's Dream",
    race: "Doll",
    gender: "Female",
    type: "NPC",
    affiliation: "None",
    characterIcon: "https://i.ibb.co/3fyQwJk/Doll.png",
    characterImage: ""
  },
  {
    name: "Darkeater Midir",
    game: "Dark Souls 3",
    origin: "Ringed City",
    race: "Dragon",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Gods",
    characterIcon: "https://i.ibb.co/TmxCjnY/midir.png",
    characterImage: ""
  },
  {
    name: "Erdtree Avatar",
    game: "Elden Ring",
    origin: "Erdtree",
    race: "Construct",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Golden Order",
    characterIcon: "https://i.ibb.co/bb0HNCx/erdtree.png",
    characterImage: ""
  },
  {
    name: "Quelaag",
    game: "Dark Souls",
    origin: "Blighttown",
    race: "Demon",
    gender: "Female",
    type: "Boss",
    affiliation: "Chaos Servants",
    characterIcon: "https://i.ibb.co/Mskrycx/quelaag.png",
    characterImage: ""
  },
  {
    name: "The Abyss Watchers",
    game: "Dark Souls 3",
    origin: "Farron Keep",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Wolf Blood",
    characterIcon: "https://i.ibb.co/LxSPsrT/watchers.png",
    characterImage: ""
  },
  {
    name: "Slave Knight Gael",
    game: "Dark Souls 3",
    origin: "The Ringed City",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "The Painted World",
    characterIcon: "https://i.ibb.co/Hh5Kw3c/Gael.png",
    characterImage: ""
  },
  {
    name: "Lorian, Elder Prince",
    game: "Dark Souls 3",
    origin: "Lothric Castle",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Royal Family of Lothric",
    characterIcon: "https://i.ibb.co/87rKjXz/Lorian.png",
    characterImage: ""
  },
  {
    name: "Celestial Emissary",
    game: "Bloodborne",
    origin: "Upper Cathedral Ward",
    race: "Kin",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Great Ones",
    characterIcon: "https://i.ibb.co/cwZN0D5/Celestial-Emissary.png",
    characterImage: ""
  },
  {
    name: "Ebrietas, Daughter of the Cosmos",
    game: "Bloodborne",
    origin: "Upper Cathedral Ward",
    race: "Kin",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Great Ones",
    characterIcon: "https://i.ibb.co/VCYJ8dq/Ebrietas.png",
    characterImage: ""
  },
  {
    name: "Astel, Naturalborn of the Void",
    game: "Elden Ring",
    origin: "Lake of Rot",
    race: "Alien",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Outer Gods",
    characterIcon: "https://i.ibb.co/YQqmVxN/Astel.png",
    characterImage: ""
  },
  {
    name: "Morgott, the Omen King",
    game: "Elden Ring",
    origin: "Leyndell",
    race: "Omen",
    gender: "Male",
    type: "Boss",
    affiliation: "Golden Order",
    characterIcon: "https://i.ibb.co/3knXpnL/Morgott.png",
    characterImage: ""
  },
  {
    name: "Margit, the Fell Omen",
    game: "Elden Ring",
    origin: "Stormhill",
    race: "Omen",
    gender: "Male",
    type: "Boss",
    affiliation: "Golden Order",
    characterIcon: "https://i.ibb.co/tPyLtGW/Margit.png",
    characterImage: ""
  },
 
  {
    name: "Demon of Hatred",
    game: "Sekiro",
    origin: "Ashina Outskirts",
    race: "Demon",
    gender: "Male",
    type: "Boss",
    affiliation: "None",
    characterIcon: "https://i.ibb.co/BNmfYXv/Hatred-Demon.png",
    characterImage: ""
  },
  {
    name: "Great Grey Wolf Sif",
    game: "Dark Souls",
    origin: "Darkroot Garden",
    race: "Wolf",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Knights of Gwyn",
    characterIcon: "https://i.ibb.co/0Mdgxp6/Sif.png",
    characterImage: ""
  },
  {
    name: "Crossbreed Priscilla",
    game: "Dark Souls",
    origin: "The Painted World of Ariamis",
    race: "Half-Dragon",
    gender: "Female",
    type: "Boss",
    affiliation: "None",
    characterIcon: "https://i.ibb.co/Sd13pfc/Priscilla.png",
    characterImage: ""
  },
  {
    name: "Seath the Scaleless",
    game: "Dark Souls",
    origin: "The Duke's Archives",
    race: "Dragon",
    gender: "Unknown",
    type: "Boss",
    affiliation: "None",
    characterIcon: "https://i.ibb.co/QdpKq28/Seath.png",
    characterImage: ""
  },
  {
    name: "Iron Golem",
    game: "Dark Souls",
    origin: "Sen's Fortress",
    race: "Construct",
    gender: "Unknown",
    type: "Boss",
    affiliation: "None",
    characterIcon: "https://i.ibb.co/vLwyjDf/Iron-Golem.png",
    characterImage: ""
  },
  {
    name: "The Twin Princes",
    game: "Dark Souls 3",
    origin: "Lothric Castle",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Royal Family of Lothric",
    characterIcon: "https://i.ibb.co/VCQZXSr/Elder-Prince.png",
    characterImage: ""
  },
  {
    name: "The Rotten",
    game: "Dark Souls 2",
    origin: "The Black Gulch",
    race: "Undead",
    gender: "Unknown",
    type: "Boss",
    affiliation: "None",
    characterIcon: "https://i.ibb.co/WVQqMsQ/The-Rotten.png",
    characterImage: ""
  },
  {
    name: "Elana, the Squalid Queen",
    game: "Dark Souls 2",
    origin: "Shulva, Sanctum City",
    race: "Human",
    gender: "Female",
    type: "Boss",
    affiliation: "Dark Souls",
    characterIcon: "https://i.ibb.co/X8TDgz9/Elana.png",
    characterImage: ""
  },
  {
    name: "Velstadt, the Royal Aegis",
    game: "Dark Souls 2",
    origin: "Undead Crypt",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "King Vendrick",
    characterIcon: "https://i.ibb.co/zb1DD7j/Velstadt.png",
    characterImage: ""
  },
  {
    name: "Manus, Father of the Abyss",
    game: "Dark Souls",
    origin: "Oolacile",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Abyss",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Kalameet",
    game: "Dark Souls",
    origin: "Royal Wood",
    race: "Dragon",
    gender: "Unknown",
    type: "Boss",
    affiliation: "None",
    characterIcon: "https://i.ibb.co/vZ7ZQkS/Kalameet.png",
    characterImage: ""
  },
  {
    name: "Elden Beast",
    game: "Elden Ring",
    origin: "The Elden Throne",
    race: "Outer God",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Erdtree",
    characterIcon: "https://i.ibb.co/cgsF6z6/Elden-Beast.png",
    characterImage: ""
  },
  {
    name: "Renalla, Queen of the Full Moon",
    game: "Elden Ring",
    origin: "Raya Lucaria Academy",
    race: "Human",
    gender: "Female",
    type: "Boss",
    affiliation: "Carian Royals",
    characterIcon: "https://i.ibb.co/ryZhqN6/Rellana.png",
    characterImage: ""
  },
  {
    name: "Melina",
    game: "Elden Ring",
    origin: "Unknown",
    race: "Human",
    gender: "Female",
    type: "NPC",
    affiliation: "The Tarnished",
    characterIcon: "https://i.ibb.co/1spntyB/Melina.png",
    characterImage: ""
  },
  {
    name: "Djura",
    game: "Bloodborne",
    origin: "Old Yharnam",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Powder Kegs",
    characterIcon: "https://i.ibb.co/k0jpXcP/Djura.png",
    characterImage: ""
  },
  {
    name: "Ludwig the Holy Blade",
    game: "Bloodborne",
    origin: "The Hunter's Nightmare",
    race: "Beast",
    gender: "Male",
    type: "Boss",
    affiliation: "The Healing Church",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "The Orphan of Kos",
    game: "Bloodborne",
    origin: "Fishing Hamlet",
    race: "Great One",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Kos",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "The Divine Dragon",
    game: "Sekiro",
    origin: "Fountainhead Palace",
    race: "Dragon",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Divinity",
    characterIcon: "https://i.ibb.co/zs3fVWq/Divine-Dragon.png",
    characterImage: ""
  },
  {
    name: "Alonne Knight Captain",
    game: "Dark Souls 2",
    origin: "Iron Keep",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Sir Alonne",
    characterIcon: "https://i.ibb.co/1vZFzhQ/Alonne-Knight-Captain.jpg",
    characterImage: ""
  },
  {
    name: "Sinh, the Slumbering Dragon",
    game: "Dark Souls 2",
    origin: "Shulva, Sanctum City",
    race: "Dragon",
    gender: "Unknown",
    type: "Boss",
    affiliation: "None",
    characterIcon: "https://i.ibb.co/p1kNFdc/sinh.png",
    characterImage: ""
  },
  {
    name: "Aldrich, Devourer of Gods",
    game: "Dark Souls 3",
    origin: "Anor Londo",
    race: "Human/Undead",
    gender: "Male",
    type: "Boss",
    affiliation: "Deep",
    characterIcon: "https://i.ibb.co/946z6sP/Aldrich.png",
    characterImage: ""
  },
  {
    name: "Yhorm the Giant",
    game: "Dark Souls 3",
    origin: "Profaned Capital",
    race: "Giant",
    gender: "Male",
    type: "Boss",
    affiliation: "Lord of Cinder",
    characterIcon: "https://i.ibb.co/XJ4GZKn/Yhorm.png",
    characterImage: ""
  },
  {
    name: "Lothric, Younger Prince",
    game: "Dark Souls 3",
    origin: "Lothric Castle",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Lothric Castle",
    characterIcon: "https://i.ibb.co/VLzxbhR/lothric.png",
    characterImage: ""
  },
  {
    name: "Laurentius of the Great Swamp",
    game: "Dark Souls",
    origin: "The Great Swamp",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Pyromancers",
    characterIcon: "https://i.ibb.co/gRGRG17/Laurentius.png",
    characterImage: ""
  },
  {
    name: "Logarius",
    game: "Bloodborne",
    origin: "Cainhurst",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Executioners",
    characterIcon: "https://i.ibb.co/7GGHm3d/Logarius.png",
    characterImage: ""
  }
];

