export const characters = [
  {
    name: "Artorias",
    game: "Dark Souls",
    origin: "Lordran",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Knights of Gwyn",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Lady Maria",
    game: "Bloodborne",
    origin: "Cainhurst",
    race: "Vileblood",
    gender: "Female",
    type: "Boss",
    affiliation: "Hunters of Byrgenwerth",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Maliketh",
    game: "Elden Ring",
    origin: "Farum Azula",
    race: "Beastman",
    gender: "Male",
    type: "Boss",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Gwyn",
    game: "Dark Souls",
    origin: "Lordran",
    race: "God",
    gender: "Male",
    type: "Boss",
    affiliation: "Lord of Sunlight",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "The Witch of Izalith",
    game: "Dark Souls",
    origin: "Lordran",
    race: "Human",
    gender: "Female",
    type: "Boss",
    affiliation: "Witches of Izalith",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Nito",
    game: "Dark Souls",
    origin: "The Tomb of the Giants",
    race: "Human/Undead",
    gender: "Male",
    type: "Boss",
    affiliation: "The Gravelord Servants",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Solaire of Astora",
    game: "Dark Souls",
    origin: "Astora",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Warrior of Sunlight",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Siegmeyer of Catarina",
    game: "Dark Souls",
    origin: "Catarina",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Knights of Catarina",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Eileen the Crow",
    game: "Bloodborne",
    origin: "Yharnam",
    race: "Human",
    gender: "Female",
    type: "NPC",
    affiliation: "Crow Hunters",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Father Gascoigne",
    game: "Bloodborne",
    origin: "Yharnam",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Hunters",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Vicar Amelia",
    game: "Bloodborne",
    origin: "Yharnam",
    race: "Beast",
    gender: "Female",
    type: "Boss",
    affiliation: "The Healing Church",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Gehrman",
    game: "Bloodborne",
    origin: "The Dream",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Hunter",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Micolash",
    game: "Bloodborne",
    origin: "Mergo's Loft",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Mensis",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Radahn",
    game: "Elden Ring",
    origin: "Caelid",
    race: "Demigod",
    gender: "Male",
    type: "Boss",
    affiliation: "Redmane",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Rykard",
    game: "Elden Ring",
    origin: "Volcano Manor",
    race: "Demigod",
    gender: "Male",
    type: "Boss",
    affiliation: "Volcano Manor",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Mohg",
    game: "Elden Ring",
    origin: "Subterranean Shunning-Grounds",
    race: "Demigod",
    gender: "Male",
    type: "Boss",
    affiliation: "Moghwyn Dynasty",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Godrick the Grafted",
    game: "Elden Ring",
    origin: "Stormveil Castle",
    race: "Human/Demigod",
    gender: "Male",
    type: "Boss",
    affiliation: "House Godrick",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Fia",
    game: "Elden Ring",
    origin: "Roundtable Hold",
    race: "Human",
    gender: "Female",
    type: "NPC",
    affiliation: "The Deathbed Companion",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Blaidd",
    game: "Elden Ring",
    origin: "Siofra River",
    race: "Wolfman",
    gender: "Male",
    type: "NPC",
    affiliation: "The Three Fingers",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Patches",
    game: "Elden Ring",
    origin: "Liurnia of the Lakes",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "None",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Vare",
    game: "Elden Ring",
    origin: "Liurnia of the Lakes",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Moor",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Yuria of Londor",
    game: "Dark Souls 3",
    origin: "Londor",
    race: "Hollow",
    gender: "Female",
    type: "NPC",
    affiliation: "The Hollowed",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Ludleth of Courland",
    game: "Dark Souls 3",
    origin: "Courland",
    race: "Hollow",
    gender: "Male",
    type: "NPC",
    affiliation: "The Firekeepers",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Nameless King",
    game: "Dark Souls 3",
    origin: "Archdragon Peak",
    race: "God/Dragon",
    gender: "Male",
    type: "Boss",
    affiliation: "The Ancient Dragons",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Pontiff Sulyvahn",
    game: "Dark Souls 3",
    origin: "Irithyll of the Boreal Valley",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Boreal Knights",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Anri of Astora",
    game: "Dark Souls 3",
    origin: "Astora",
    race: "Human",
    gender: "Female",
    type: "NPC",
    affiliation: "Fledgling Knight",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Siegward of Catarina",
    game: "Dark Souls 3",
    origin: "Catarina",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Knights of Catarina",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Shura",
    game: "Sekiro",
    origin: "Ashina Castle",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Ashina",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Isshin Ashina",
    game: "Sekiro",
    origin: "Ashina Castle",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Ashina Clan",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Genichiro Ashina",
    game: "Sekiro",
    origin: "Ashina Castle",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Ashina Clan",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Emma",
    game: "Sekiro",
    origin: "Ashina Castle",
    race: "Human",
    gender: "Female",
    type: "NPC",
    affiliation: "Heir to the Dragon",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Sekiro",
    game: "Sekiro",
    origin: "Ashina",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Shinobi",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Bloodborne Hunter",
    game: "Bloodborne",
    origin: "Yharnam",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Hunters",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Godo",
    game: "Sekiro",
    origin: "Senpou Temple",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Senpou Temple",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Kuro",
    game: "Sekiro",
    origin: "Ashina Castle",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Shinobi",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Oda Nobunaga",
    game: "Sekiro",
    origin: "Sengoku Japan",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Warlord",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Tarnished",
    game: "Elden Ring",
    origin: "Unknown",
    race: "Human",
    gender: "Varies",
    type: "NPC",
    affiliation: "Varies",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Laurence, the First Vicar",
    game: "Bloodborne",
    origin: "Yharnam",
    race: "Beast",
    gender: "Male",
    type: "Boss",
    affiliation: "The Healing Church",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Ornstein",
    game: "Dark Souls",
    origin: "Lordran",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Knights of Gwyn",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Smough",
    game: "Dark Souls",
    origin: "Lordran",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Executioners",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Malenia",
    game: "Elden Ring",
    origin: "Haligtree",
    race: "Demigod",
    gender: "Female",
    type: "Boss",
    affiliation: "Haligtree Knights",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Ranni the Witch",
    game: "Elden Ring",
    origin: "Liurnia of the Lakes",
    race: "Empyrean",
    gender: "Female",
    type: "NPC",
    affiliation: "Carian Royal Family",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Gyoubu Masataka Oniwa",
    game: "Sekiro",
    origin: "Ashina",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Ashina Clan",
    characterIcon: "",
    characterImage: "https://i.ibb.co/9vFftdj/GyoubuBG.png"
  },
  {
    name: "Lady Butterfly",
    game: "Sekiro",
    origin: "Hirata Estate",
    race: "Human",
    gender: "Female",
    type: "Boss",
    affiliation: "Shinobi",
    characterIcon: "",
    characterImage: "https://i.ibb.co/DKcBX0K/Butter-Fly-BG.png"
  },
  {
    name: "The Doll",
    game: "Bloodborne",
    origin: "Hunter's Dream",
    race: "Doll",
    gender: "Female",
    type: "NPC",
    affiliation: "None",
    characterIcon: "",
    characterImage: "https://i.ibb.co/xLTdmkM/DollBG.png"
  },
  {
    name: "Darkeater Midir",
    game: "Dark Souls 3",
    origin: "Ringed City",
    race: "Dragon",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Gods",
    characterIcon: "",
    characterImage: "https://i.ibb.co/dMPFnqc/MidirBG.png"
  },
  {
    name: "Erdtree Avatar",
    game: "Elden Ring",
    origin: "Erdtree",
    race: "Construct",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Golden Order",
    characterIcon: "",
    characterImage: "https://i.ibb.co/31s55x5/Erdtree-BG.png"
  },
  {
    name: "Quelaag",
    game: "Dark Souls",
    origin: "Blighttown",
    race: "Demon",
    gender: "Female",
    type: "Boss",
    affiliation: "Chaos Servants",
    characterIcon: "",
    characterImage: "https://i.ibb.co/pd9fFNY/Quelaag-BG.png"
  },
  {
    name: "The Abyss Watchers",
    game: "Dark Souls 3",
    origin: "Farron Keep",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Wolf Blood",
    characterIcon: "",
    characterImage: "https://i.ibb.co/YB0D2Nn/AbyssBG.png"
  },
  {
    name: "Slave Knight Gael",
    game: "Dark Souls 3",
    origin: "The Ringed City",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "The Painted World",
    characterIcon: "",
    characterImage: "https://i.ibb.co/dt5RHZx/GaelBG.png"
  },
  {
    name: "Lorian, Elder Prince",
    game: "Dark Souls 3",
    origin: "Lothric Castle",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Royal Family of Lothric",
    characterIcon: "",
    characterImage: "https://i.ibb.co/sHk4w8V/LorianBG.png"
  },
  {
    name: "Celestial Emissary",
    game: "Bloodborne",
    origin: "Upper Cathedral Ward",
    race: "Kin",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Great Ones",
    characterIcon: "",
    characterImage: "https://i.ibb.co/rttCFGC/Emissary-BG.png"
  },
  {
    name: "Ebrietas, Daughter of the Cosmos",
    game: "Bloodborne",
    origin: "Upper Cathedral Ward",
    race: "Kin",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Great Ones",
    characterIcon: "",
    characterImage: "https://i.ibb.co/t8YLgWX/Ebrietas-BG.png"
  },
  {
    name: "Astel, Naturalborn of the Void",
    game: "Elden Ring",
    origin: "Lake of Rot",
    race: "Alien",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Outer Gods",
    characterIcon: "",
    characterImage: "https://i.ibb.co/ns1wGH3/AnstelBG.png"
  },
  {
    name: "Morgott, the Omen King",
    game: "Elden Ring",
    origin: "Leyndell",
    race: "Omen",
    gender: "Male",
    type: "Boss",
    affiliation: "Golden Order",
    characterIcon: "",
    characterImage: "https://i.ibb.co/vLbtRvt/Morgott-BG.png"
  },
  {
    name: "Margit, the Fell Omen",
    game: "Elden Ring",
    origin: "Stormhill",
    race: "Omen",
    gender: "Male",
    type: "Boss",
    affiliation: "Golden Order",
    characterIcon: "",
    characterImage: "https://i.ibb.co/HxYWQXS/MargitBG.png"
  },
 
  {
    name: "Demon of Hatred",
    game: "Sekiro",
    origin: "Ashina Outskirts",
    race: "Demon",
    gender: "Male",
    type: "Boss",
    affiliation: "None",
    characterIcon: "",
    characterImage: "https://i.ibb.co/KNrttDv/Hatred-Demon-BG.png"
  },
  {
    name: "The Great Grey Wolf Sif",
    game: "Dark Souls",
    origin: "Darkroot Garden",
    race: "Wolf",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Knights of Gwyn",
    characterIcon: "",
    characterImage: "https://i.ibb.co/55KqKYC/SifBG.png"
  },
  {
    name: "Crossbreed Priscilla",
    game: "Dark Souls",
    origin: "The Painted World of Ariamis",
    race: "Half-Dragon",
    gender: "Female",
    type: "Boss",
    affiliation: "None",
    characterIcon: "",
    characterImage: "https://i.ibb.co/xCrMkCS/Priscilla-BG.png"
  },
  {
    name: "Seath the Scaleless",
    game: "Dark Souls",
    origin: "The Duke's Archives",
    race: "Dragon",
    gender: "Unknown",
    type: "Boss",
    affiliation: "None",
    characterIcon: "",
    characterImage: "https://i.ibb.co/NpB5Kh6/SeathBG.png"
  },
  {
    name: "Iron Golem",
    game: "Dark Souls",
    origin: "Sen's Fortress",
    race: "Construct",
    gender: "Unknown",
    type: "Boss",
    affiliation: "None",
    characterIcon: "",
    characterImage: "https://i.ibb.co/b6trQZY/GolemBG.png"
  },
  {
    name: "The Twin Princes",
    game: "Dark Souls 3",
    origin: "Lothric Castle",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Royal Family of Lothric",
    characterIcon: "",
    characterImage: "https://i.ibb.co/Km4FGVd/TwinkBG.png"
  },
  {
    name: "The Rotten",
    game: "Dark Souls 2",
    origin: "The Black Gulch",
    race: "Undead",
    gender: "Unknown",
    type: "Boss",
    affiliation: "None",
    characterIcon: "",
    characterImage: "https://i.ibb.co/HXHtd9j/RottenBG.png"
  },
  {
    name: "Elana, the Squalid Queen",
    game: "Dark Souls 2",
    origin: "Shulva, Sanctum City",
    race: "Human",
    gender: "Female",
    type: "Boss",
    affiliation: "Dark Souls",
    characterIcon: "",
    characterImage: "https://i.ibb.co/QC9CCtq/ElanaBG.png"
  },
  {
    name: "Velstadt, the Royal Aegis",
    game: "Dark Souls 2",
    origin: "Undead Crypt",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "King Vendrick",
    characterIcon: "",
    characterImage: "https://i.ibb.co/WyhWZSY/Velstadt-BG.png"
  },
  {
    name: "Manus, Father of the Abyss",
    game: "Dark Souls",
    origin: "Oolacile",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Abyss",
    characterIcon: "https://i.ibb.co/tLdDNjr/Manus.png",
    characterImage: "https://i.ibb.co/Jn3smpc/ManusBG.png"
  },
  {
    name: "Kalameet",
    game: "Dark Souls",
    origin: "Royal Wood",
    race: "Dragon",
    gender: "Unknown",
    type: "Boss",
    affiliation: "None",
    characterIcon: "",
    characterImage: "https://i.ibb.co/MPT9fFF/Kalameet-BG.png"
  },
  {
    name: "Elden Beast",
    game: "Elden Ring",
    origin: "The Elden Throne",
    race: "Outer God",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Erdtree",
    characterIcon: "",
    characterImage: "https://i.ibb.co/Wv2v7MP/Elden-Beast-BG.png"
  },
  {
    name: "Renalla, Queen of the Full Moon",
    game: "Elden Ring",
    origin: "Raya Lucaria Academy",
    race: "Human",
    gender: "Female",
    type: "Boss",
    affiliation: "Carian Royals",
    characterIcon: "",
    characterImage: "https://i.ibb.co/8KBXjXz/Rennala-BG.png"
  },
  {
    name: "Melina",
    game: "Elden Ring",
    origin: "Unknown",
    race: "Human",
    gender: "Female",
    type: "NPC",
    affiliation: "The Tarnished",
    characterIcon: "",
    characterImage: "https://i.ibb.co/1m49bqw/MelinaBG.png"
  },
  {
    name: "Djura",
    game: "Bloodborne",
    origin: "Old Yharnam",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Powder Kegs",
    characterIcon: "",
    characterImage: "https://i.ibb.co/9vrJN6L/DjuraBG.png"
  },
  {
    name: "Ludwig the Holy Blade",
    game: "Bloodborne",
    origin: "The Hunter's Nightmare",
    race: "Beast",
    gender: "Male",
    type: "Boss",
    affiliation: "The Healing Church",
    characterIcon: "https://i.ibb.co/8NpNQrN/Ludwig.png",
    characterImage: "https://i.ibb.co/v4YZ8D5/LudwigBG.png"
  },
  {
    name: "The Orphan of Kos",
    game: "Bloodborne",
    origin: "Fishing Hamlet",
    race: "Great One",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Kos",
    characterIcon: "https://i.ibb.co/WGNJm2V/Ophan.png",
    characterImage: "https://i.ibb.co/pWnjkf1/OphanBG.png"
  },
  {
    name: "Gyoubu Masataka Oniwa",
    game: "Sekiro",
    origin: "Ashina",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Ashina Clan",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "The Divine Dragon",
    game: "Sekiro",
    origin: "Fountainhead Palace",
    race: "Dragon",
    gender: "Unknown",
    type: "Boss",
    affiliation: "Divinity",
    characterIcon: "",
    characterImage: "https://i.ibb.co/7rQJtXk/Divine-Dragon-BG.png"
  },
  {
    name: "Alonne Knight Captain",
    game: "Dark Souls 2",
    origin: "Iron Keep",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Sir Alonne",
    characterIcon: "",
    characterImage: "https://i.ibb.co/CwMbMDS/Allone-Knight-BG.png"
  },
  {
    name: "Sinh, the Slumbering Dragon",
    game: "Dark Souls 2",
    origin: "Shulva, Sanctum City",
    race: "Dragon",
    gender: "Unknown",
    type: "Boss",
    affiliation: "None",
    characterIcon: "",
    characterImage: "https://i.ibb.co/QNHBN3N/Sinh.png"
  },
  {
    name: "Aldrich, Devourer of Gods",
    game: "Dark Souls 3",
    origin: "Anor Londo",
    race: "Human/Undead",
    gender: "Male",
    type: "Boss",
    affiliation: "Deep",
    characterIcon: "",
    characterImage: "https://i.ibb.co/6rxg05B/Aldrich-BG.png"
  },
  {
    name: "Yhorm the Giant",
    game: "Dark Souls 3",
    origin: "Profaned Capital",
    race: "Giant",
    gender: "Male",
    type: "Boss",
    affiliation: "Lord of Cinder",
    characterIcon: "",
    characterImage: "https://i.ibb.co/cgV8pC8/Yhorm.png"
  },
  {
    name: "Lothric, Younger Prince",
    game: "Dark Souls 3",
    origin: "Lothric Castle",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Lothric Castle",
    characterIcon: "",
    characterImage: ""
  },
  {
    name: "Laurentius of the Great Swamp",
    game: "Dark Souls",
    origin: "The Great Swamp",
    race: "Human",
    gender: "Male",
    type: "NPC",
    affiliation: "Pyromancers",
    characterIcon: "",
    characterImage: "https://i.ibb.co/Fgb3Dgw/Laurentius-BG.png"
  },
  {
    name: "Logarius",
    game: "Bloodborne",
    origin: "Cainhurst",
    race: "Human",
    gender: "Male",
    type: "Boss",
    affiliation: "Executioners",
    characterIcon: "",
    characterImage: "https://i.ibb.co/tbNCW1g/Logarius-BG.png"
  }
];

